/*************************************************************************************************************************
 * Created by: Holtek Touch MCU Workshop, Version 3.5.2.0
 * TKS_GLOBE_VARIES.H
 * 10:58:02 AM Sunday, September 29, 2019
*************************************************************************************************************************/
#include <BS66F360.h>
#define _BS66F360_
#define _V413_
#define SystemClock     0
// Components' settings ...
