; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.0.0
; USER_PROGRAM.inc
; 10:46:12 AM Sunday, June 02, 2019
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "..\BS66F360_LIBV413\BS66F360_LIBV413.aex" 
#include "..\MAIN_PROGRAM_V104\MAIN_PROGRAM_V104.aex" 
